#!/usr/bin/env python
# coding: utf-8

# In[29]:


import pandas as pd
import numpy as np


# In[19]:


a = {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
}

authors  = pd.DataFrame(a)

authors 


# In[20]:


a = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title ": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    "price": [450, 300, 350, 500, 450, 370, 290]
}

book = pd.DataFrame(a)

book  


# In[21]:


authors_price = authors.merge(book, left_on="author_id", right_on="author_id", how="left")
authors_price


# In[22]:


top5 = authors_price.nlargest(5, "price")
top5


# In[23]:


df1 = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price':'min_price'})
df1
df2 = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price':'max_price'})
df2
df3 = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price':'mean_price'})
df3

authors_stat = pd.concat([df1, df2, df3], axis = 1)
authors_stat


# In[24]:


authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'] 
authors_price


# In[42]:


book_info = pd.pivot_table(authors_price, index=['author_name'], values="price", columns=['cover'], aggfunc=np.sum,
                           fill_value=0)
book_info


# In[39]:


get_ipython().run_line_magic('pinfo', 'pd.pivot_table')


# In[43]:


book_info.to_pickle("book_info.pkl")


# In[44]:


book_info2 = pd.read_pickle("book_info.pkl")


# In[45]:


book_info2


# In[ ]:




