#!/usr/bin/env python
# coding: utf-8

# In[ ]:


#Импортируйте библиотеки pandas и numpy.


# In[1]:


import numpy as np
import pandas as pd


# In[13]:


#Загрузите "Boston House Prices dataset" из встроенных наборов данных библиотеки sklearn.
#Создайте датафреймы X и y из этих данных.


# In[7]:


from sklearn.datasets import load_boston
boston = load_boston()


# In[ ]:


#Разбейте эти датафреймы на тренировочные (X_train, y_train) и тестовые (X_test, y_test) с помощью функции train_test_split так,
#чтобы размер тестовой выборки


# In[10]:


X = pd.DataFrame(boston.data, columns=boston.feature_names)
y = boston.target


# In[ ]:


#составлял 30% от всех данных, при этом аргумент random_state должен быть равен 42.


# In[11]:


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape


# In[ ]:


#Создайте модель линейной регрессии под названием lr с помощью класса LinearRegression из модуля sklearn.linear_model.


# In[12]:


from sklearn.linear_model import LinearRegression
lr = LinearRegression()


# In[ ]:


#Обучите модель на тренировочных данных (используйте все признаки) и сделайте предсказание на тестовых.


# In[14]:


lr.fit(X_train, y_train)


# In[20]:


y_pred = lr.predict(X_test)
y_pred.shape


# In[21]:





# In[ ]:


#Вычислите R2 полученных предказаний с помощью r2_score из модуля sklearn.metrics.


# In[23]: